# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a91ca6d3601f69b7bf6c41f8cd51dca10b48281dbfd6a9f18a71b7b60c27bf6b69d6446b57a45c5404ca33984a639fc019bf0b08a25ed2256787fae289fef57

test:
  secret_key_base: f40940f757467b09c995bf2d5915e90537cc8cc22e86d31d11ea89ebfdb28222f29532a3ffbcce2e476eb893a088a2e85335a5a6292eaeb7eecfa9b2e762d6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
